import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class ReportService {
  /// Generates and previews a PDF report for a specific batch or farm overview
  static Future<void> generateFarmReport({
    required String farmName,
    required List<dynamic> batches,
    required List<dynamic> sales,
    required List<dynamic> mortality,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final formatter = DateFormat('yyyy-MM-dd HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('KukuFiti Farm Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Text(formatter.format(now)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Text('Farm: $farmName', style: pw.TextStyle(fontSize: 18)),
          pw.Divider(),
          pw.SizedBox(height: 20),
          
          pw.Text('Active Batches Summary', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.TableHelper.fromTextArray(
            headers: ['Batch Name', 'Size', 'Status', 'Start Date'],
            data: batches.map((b) => [
              b['name'] ?? 'N/A',
              b['initial_count']?.toString() ?? b['batch_size']?.toString() ?? '0',
              b['status']?.toString().toUpperCase() ?? 'ACTIVE',
              b['start_date'] ?? 'N/A',
            ]).toList(),
          ),
          
          pw.SizedBox(height: 30),
          pw.Text('Financial Performance (Sales)', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.TableHelper.fromTextArray(
            headers: ['Date', 'Buyer', 'Qty', 'Amount (KES)'],
            data: sales.take(10).map((s) => [
              s['date']?.toString().split('T')[0] ?? 'N/A',
              s['buyer'] ?? 'Walk-in',
              s['quantity']?.toString() ?? '0',
              s['amount']?.toString() ?? '0',
            ]).toList(),
          ),

          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 20),
            child: pw.Footer(
              trailing: pw.Text('Generated by KukuFiti Mobile App', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
            ),
          ),
        ],
      ),
    );

    // This opens the native share/print dialog immediately
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'KukuFiti_Report_${DateFormat('yyyyMMdd').format(now)}.pdf',
    );
  }
}
